name = "Sam Walker"
location = "Vail, Co"
favorite_activity = "skiing"
age = 32
weight = 185
height_in_cm = 181
actual_weight = 187.5
temperature_f = 37.4
water_drank_oz = 64.7
is_male = true
is_hungry = true
is_mad = false